---
    - name: Ensure ZSH installed
      apt: pkg=zsh state=latest

    - name: Get ZSH
      shell: creates="/home/vagrant/.oh-my-zsh" su - vagrant -c 'wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sed -n '/chsh/!p' | zsh'

    - name: Change theme for vagrant user
      shell: sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="jreese"/' /home/vagrant/.zshrc

    - name: Change default shell for vagrant user
      shell: chsh vagrant -s $(which zsh)
      ignore_errors: yes

    - name: Get ZSH for root
      shell: creates="/root/.oh-my-zsh" sudo su - root -c 'wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sed -n '/chsh/!p' | zsh'

    - name: Change theme for root
      shell: sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="jreese"/' /root/.zshrc

    - name: Change default shell for root
      shell: chsh root -s $(which zsh)
      ignore_errors: yes

    - name: Copy fixed ZSH theme (without GIT dirty status slownes on Vagrant)
      copy: src=jreese.zsh-theme dest={{ item }}/.oh-my-zsh/themes/jreese.zsh-theme mode=0644
      with_items:
        - /home/vagrant
        - /root