- name: "Activate Ruby {{rbenv_ruby_version}} and Setup Gems"
  shell: "{{item}}"
  args:
    executable: /bin/bash
    chdir: /vagrant
  environment:
    PATH: "{{rbenv_root}}/shims:{{rbenv_root}}/bin:/bin:/usr/bin:/usr/local/bin:$PATH"
  with_items:
  - gem i bundler
  - rbenv rehash
  - bundle install

- name: Setup DB
  shell: rake db:create db:migrate
  sudo: false
  args:
    executable: /bin/bash
    chdir: /vagrant
  environment:
    PATH: "{{rbenv_root}}/shims:{{rbenv_root}}/bin:/bin:/usr/bin:/usr/local/bin:$PATH"