#- name: Copy nginx sites-available/default
#  template: src=default.j2 dest=/etc/nginx/sites-available/default owner=root group=root mode=0644

- name: Copy nginx sites-available/univer
  template: src=app.j2 dest=/etc/nginx/sites-available/univer owner=root group=root mode=0644

- name: Create symlink to univer
  file: src=/etc/nginx/sites-available/univer dest=/etc/nginx/sites-enabled/univer state=link

- name: Restart nginx
  service: name=nginx state=restarted