development: &default
  adapter: postgresql
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: journal_test
