development: &default
  adapter: postgresql
  database: univer_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *default
  database: univer

production:
  <<: *default
  database: univer_staging

test:
  <<: *default
  database: univer_test
