# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: 9826aea558d3159d7817f743e28f369a39a9d4d1e1449528575d6a8ae4a4ef8f79332df53a64100a7b735b84578d99ab05d02d0a026cd048631d1e74730f9d8e
  host: univer.local:3000
  asset_host: univer.local:3000

  database: &database
    host: localhost
    name: univer_development
    username:
    password:

  smtp: &smtp
    address: smtp.mandrillapp.com
    domain: univer-journal.org
    password: 7JjoTQUVVG3qWb9rBGCkpg
    username: desgnkiss@gmail.com

# DEVELOPMENT
development:
  <<: *default

# TEST
test:
  <<: *default
  database:
    <<: *database
    name: univer_test

# PRODUCTION
production:
  <<: *default
  host: univer-journal.org
  asset_host: univer-journal.org

  database: &database
    host: localhost
    name: univer_production
    username: univer_user
    password: CXGSYVKq776nuX5W

