# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 9826aea558d3159d7817f743e28f369a39a9d4d1e1449528575d6a8ae4a4ef8f79332df53a64100a7b735b84578d99ab05d02d0a026cd048631d1e74730f9d8e

test:
  domain_name: example.com 
  secret_key_base: 5c55573cebe973847e1c3f0956558fa2e23fd8993ba7640ca531b091fe1d403262dc3317bd1abe0150349a815cf4df3794abae4080c5fe4d0b1def0fca97f1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
